export const PROJECT_DIRECTORIES = [
  "00_INBOX",
  "01_BIBLIA",
  "02_PERSONAJES",
  "03_MUNDO/reinos",
  "03_MUNDO/lugares",
  "03_MUNDO/culturas",
  "03_MUNDO/facciones",
  "03_MUNDO/historia",
  "03_MUNDO/criaturas",
  "04_MAGIA/tipos_de_magia",
  "04_MAGIA/artefactos",
  "05_CRONOLOGIA",
  "06_TRAMA",
  "07_ESCENAS",
  "08_CAPITULOS",
  "09_REVISION",
  "99_ARCHIVO",
] as const;

const EMPTY = "";
const INDEX = "# Índice\n\n";
const STATUS_FRONTMATTER = "---\nid:\ntipo:\nestado: BORRADOR\naliases: []\n---\n\n";

export const PROJECT_FILES: Readonly<Record<string, string>> = {
  "README.md": "# Proyecto SUMI\n\nEste proyecto usa Markdown como fuente de verdad.\n",
  "00_INBOX/ideas_sueltas.md": "# Ideas sueltas\n\n",
  "01_BIBLIA/INDEX.md": INDEX,
  "01_BIBLIA/premisa.md": EMPTY,
  "01_BIBLIA/tono_y_estilo.md": EMPTY,
  "01_BIBLIA/temas.md": EMPTY,
  "01_BIBLIA/canon_global.md": EMPTY,
  "01_BIBLIA/glosario.md": EMPTY,
  "01_BIBLIA/preguntas_pendientes.md": EMPTY,
  "02_PERSONAJES/INDEX.md": INDEX,
  "02_PERSONAJES/_PLANTILLA_PERSONAJE.md": `${STATUS_FRONTMATTER}# Nombre del personaje\n\n## Función narrativa\n\n## Personalidad\n\n## Objetivos\n\n## Motivaciones\n\n## Relaciones\n\n## Arco narrativo\n\n## Notas\n`,
  "03_MUNDO/INDEX.md": INDEX,
  "03_MUNDO/_PLANTILLA_LUGAR.md": `${STATUS_FRONTMATTER}# Nombre del lugar\n\n## Descripción\n\n## Notas\n`,
  "04_MAGIA/INDEX.md": INDEX,
  "04_MAGIA/sistema_general.md": EMPTY,
  "04_MAGIA/reglas.md": EMPTY,
  "04_MAGIA/costes_y_limites.md": EMPTY,
  "04_MAGIA/_PLANTILLA_MAGIA.md": `${STATUS_FRONTMATTER}# Nombre del elemento mágico\n\n## Descripción\n\n## Notas\n`,
  "05_CRONOLOGIA/INDEX.md": INDEX,
  "05_CRONOLOGIA/cronologia_general.md": EMPTY,
  "05_CRONOLOGIA/_PLANTILLA_EVENTO.md": `${STATUS_FRONTMATTER}# Nombre del evento\n\n## Fecha\n\n## Descripción\n`,
  "06_TRAMA/INDEX.md": INDEX,
  "06_TRAMA/trama_principal.md": EMPTY,
  "06_TRAMA/subtramas.md": EMPTY,
  "06_TRAMA/arcos_de_personaje.md": EMPTY,
  "06_TRAMA/conflictos.md": EMPTY,
  "06_TRAMA/misterios_y_revelaciones.md": EMPTY,
  "06_TRAMA/preguntas_sin_resolver.md": EMPTY,
  "07_ESCENAS/INDEX.md": INDEX,
  "07_ESCENAS/_PLANTILLA_ESCENA.md": `${STATUS_FRONTMATTER}# Nombre de la escena\n\n## Propósito\n\n## Notas\n`,
  "08_CAPITULOS/INDEX.md": INDEX,
  "08_CAPITULOS/_PLANTILLA_CAPITULO.md": `${STATUS_FRONTMATTER}# Capítulo\n\n## Escenas\n\n## Notas\n`,
  "09_REVISION/continuidad.md": EMPTY,
  "09_REVISION/contradicciones.md": EMPTY,
  "09_REVISION/pendientes.md": EMPTY,
  "99_ARCHIVO/README.md": "# Archivo\n\n",
};
